### ISSUE TITLE
avgRepeats on ODs

### ISSUE THREAD

**Issue by dmweld** [weldlabucsb/DataAnalysis#8]
It would be cool if we could use avgRepeats to average together entire OD images, not just scalar variables.  

Let me know if I'm githubbing wrong; I think this is my first issue.

**Comment by jpagett** [comment]
Github'd correctly, assign me at top right if you want me to get notifications.

This functionality is already supported -- provide 'OD' as one of the variables-to-be-averaged (the third argument).

```matlab
avgRepeats( RunData, varied_variable, { 'summedODy', 'OD' } )
```
